# dependencies

In [1]:
import duckdb
import pandas as pd
import numpy as np

In [2]:
con = duckdb.connect('data/exploitation.db')

# some exploration

In [3]:
con.execute("show tables").fetchall()

[('houses',)]

In [19]:
df = con.execute("select * from houses limit 10").df()
df2 = con.execute("select * from houses").df()
df

,id,url,region,region_url,price,type,sqfeet,beds,baths,cats_allowed,...,hospital_type_children,government_hospital,nonprofit_hospital,private_hospital,num_schools,num_students,preschool,elementary_school,middle_school,high_school
0,7051152434,https://portland.craigslist.org/wsc/apa/d/port...,portland,https://portland.craigslist.org,1350.0,apartment,1100.0,2,2.0,Yes,...,1.0,3.0,13.0,2.0,403,240366.0,261.0,64.0,61.0,14.0
1,7051146105,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2725.0,apartment,1172.0,2,2.0,Yes,...,1.0,4.0,16.0,2.0,509,309619.0,312.0,81.0,84.0,30.0
2,7051135375,https://portland.craigslist.org/wsc/apa/d/hill...,portland,https://portland.craigslist.org,1630.0,apartment,1030.0,2,2.0,Yes,...,3.0,12.0,48.0,6.0,1431,851145.0,888.0,222.0,237.0,78.0
3,7051134300,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1768.0,apartment,1286.0,2,2.5,Yes,...,44.0,88.0,352.0,88.0,13640,8113424.0,8404.0,2288.0,2332.0,528.0
4,7051104814,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1384.0,apartment,533.0,0,1.0,Yes,...,6.0,24.0,96.0,12.0,3012,1826880.0,1836.0,480.0,504.0,180.0
5,7051112739,https://portland.craigslist.org/clk/apa/d/vanc...,portland,https://portland.craigslist.org,3250.0,house,2895.0,4,3.0,Yes,...,1.0,4.0,10.0,1.0,335,193095.0,193.0,55.0,60.0,26.0
6,7039764729,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1640.0,apartment,1204.0,3,2.0,Yes,...,3.0,12.0,48.0,6.0,1488,892032.0,921.0,234.0,243.0,81.0
7,7051064155,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1515.0,apartment,1045.0,2,2.0,Yes,...,44.0,88.0,352.0,88.0,13640,8113424.0,8404.0,2288.0,2332.0,528.0
8,7051050052,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2200.0,duplex,1100.0,3,2.0,No,...,6.0,24.0,96.0,12.0,3012,1826880.0,1836.0,480.0,504.0,180.0
9,7045835490,https://portland.craigslist.org/mlt/apa/d/gres...,portland,https://portland.craigslist.org,1205.0,apartment,865.0,2,1.0,Yes,...,4.0,16.0,60.0,8.0,1988,1206692.0,1192.0,328.0,336.0,124.0

In [15]:
df[df.columns[0:10]]

,id,url,region,region_url,price,type,sqfeet,beds,baths,cats_allowed
0,7051152434,https://portland.craigslist.org/wsc/apa/d/port...,portland,https://portland.craigslist.org,1350.0,apartment,1100.0,2,2.0,Yes
1,7051146105,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2725.0,apartment,1172.0,2,2.0,Yes
2,7051135375,https://portland.craigslist.org/wsc/apa/d/hill...,portland,https://portland.craigslist.org,1630.0,apartment,1030.0,2,2.0,Yes
3,7051134300,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1768.0,apartment,1286.0,2,2.5,Yes
4,7051104814,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1384.0,apartment,533.0,0,1.0,Yes
5,7051112739,https://portland.craigslist.org/clk/apa/d/vanc...,portland,https://portland.craigslist.org,3250.0,house,2895.0,4,3.0,Yes
6,7039764729,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1640.0,apartment,1204.0,3,2.0,Yes
7,7051064155,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1515.0,apartment,1045.0,2,2.0,Yes
8,7051050052,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2200.0,duplex,1100.0,3,2.0,No
9,7045835490,https://portland.craigslist.org/mlt/apa/d/gres...,portland,https://portland.craigslist.org,1205.0,apartment,865.0,2,1.0,Yes

les columnes que té sentit filtrar en la sandbox son 'region', 'type' i 'state'. realment de region, hi ha 404 regions, potser en son bastantes

potser també longitud i latitud

la resta són numèriques, ids, urls i coses

In [20]:
np.unique(df2.state)

array(['ak', 'al', 'ar', 'az', 'ca', 'co', 'ct', 'dc', 'de', 'fl', 'ga',
       'hi', 'ia', 'id', 'il', 'in', 'ks', 'ky', 'la', 'ma', 'md', 'me',
       'mi', 'mn', 'mo', 'ms', 'mt', 'nc', 'nd', 'ne', 'nh', 'nj', 'nm',
       'nv', 'ny', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx',
       'ut', 'va', 'vt', 'wa', 'wi', 'wv', 'wy'], dtype=object)

In [21]:
np.unique(df2.type)

array(['apartment', 'assisted living', 'condo', 'cottage/cabin', 'duplex',
       'flat', 'house', 'in-law', 'land', 'loft', 'manufactured',
       'townhouse'], dtype=object)

# do the query

In [83]:
types = [] # default values
states = []

In [90]:
types = ["house", "apartment"]
states = "or"

In [91]:
# set the correct data types

if type(types) == str:
    types = [types]
elif type(types) == list:
    pass
else: types = list(types)

if type(states) == str:
    states = [states]
elif type(states) == list:
    pass
else: states = list(states)

In [92]:
# do the query

query_where = []
if len(types) > 0:
    query_where.append("type in (" + ",".join(["'"+x+"'" for x in types]) + ")")
if len(states) > 0:
    query_where.append("state in (" + ",".join(["'"+x+"'" for x in states]) + ")")

if len(query_where) > 0:
    query_where = " where " + " and ".join(query_where)
else:
    query_where = ""

query = "select * from houses" + query_where
query

"select * from houses where type in ('house','apartment') and state in ('or')"

In [93]:
# name of the table
types
table_name = "sandbox"

if len(types)>0:
    table_name = table_name + "_T" + "".join([
        "_" + x.replace('/','').replace('-','').replace(' ','')
        for x in types ])

if len(states)>0:
    table_name = table_name + "_S" + "".join([ "_" + x for x in states ])

table_name

'sandbox_T_house_apartment_S_or'

In [94]:
# apply the query

con.execute(f"create or replace table {table_name} as ( {query} )")

In [4]:
con.close()

In [97]:
print(table_name)
con.execute("select * from sandbox_T_house_apartment_S_or").df()

sandbox_T_house_apartment_S_or

,id,url,region,region_url,price,type,sqfeet,beds,baths,cats_allowed,...,hospital_type_children,government_hospital,nonprofit_hospital,private_hospital,num_schools,num_students,preschool,elementary_school,middle_school,high_school
0,7051112739,https://portland.craigslist.org/clk/apa/d/vanc...,portland,https://portland.craigslist.org,3250.0,house,2895.0,4,3.0,Yes,...,1.0,4.0,10.0,1.0,335,193095.0,193.0,55.0,60.0,26.0
1,7043499211,https://bend.craigslist.org/apa/d/bend-rossby-...,bend,https://bend.craigslist.org,1895.0,house,1400.0,3,2.0,No,...,0.0,0.0,2.0,0.0,35,22958.0,20.0,7.0,7.0,1.0
2,7050677982,https://bend.craigslist.org/apa/d/bend-dreamy-...,bend,https://bend.craigslist.org,2400.0,house,2130.0,4,2.5,Yes,...,0.0,0.0,63.0,0.0,1827,1187424.0,1071.0,378.0,378.0,0.0
3,7032126537,https://bend.craigslist.org/apa/d/bend-darling...,bend,https://bend.craigslist.org,1595.0,house,1462.0,3,2.0,No,...,0.0,0.0,0.0,0.0,7,1943.0,4.0,1.0,2.0,0.0
4,7038053793,https://bend.craigslist.org/apa/d/bend-warm-an...,bend,https://bend.craigslist.org,1900.0,house,1200.0,3,1.0,No,...,0.0,0.0,126.0,0.0,2331,1520505.0,1323.0,504.0,441.0,63.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7236,7028144480,https://salem.craigslist.org/apa/d/dallas-avai...,salem,https://salem.craigslist.org,995.0,apartment,750.0,2,1.0,Yes,...,0.0,1.0,5.0,0.0,139,72396.0,82.0,25.0,23.0,9.0
7237,7040309767,https://salem.craigslist.org/apa/d/keizer-mana...,salem,https://salem.craigslist.org,1050.0,apartment,927.0,2,1.0,Yes,...,0.0,7.0,28.0,7.0,1127,581959.0,623.0,210.0,210.0,84.0
7238,7024849466,https://salem.craigslist.org/apa/d/salem-house...,salem,https://salem.craigslist.org,255000.0,house,1250.0,3,2.0,No,...,0.0,24.0,96.0,24.0,3648,1906368.0,2064.0,720.0,624.0,240.0
7239,7039275469,https://salem.craigslist.org/apa/d/salem-singl...,salem,https://salem.craigslist.org,1700.0,house,1832.0,3,2.0,Yes,...,0.0,1.0,4.0,1.0,146,77643.0,82.0,29.0,25.0,10.0
7240,7014943226,https://medford.craigslist.org/apa/d/medford-a...,medford-ashland,https://medford.craigslist.org,1199.0,apartment,453.0,1,1.0,Yes,...,0.0,0.0,32.0,0.0,1344,632944.0,800.0,192.0,256.0,80.0

# help function

In [88]:
def sandbox_generator_help(col="all") :
    if col=="state":
        print("valid states: 'ak', 'al', 'ar', 'az', 'ca', 'co', 'ct', 'dc', 'de', " +
        "'fl', 'ga', 'hi', 'ia', 'id', 'il', 'in', 'ks', 'ky', 'la', 'ma', 'md', " +
        "'me', 'mi', 'mn', 'mo', 'ms', 'mt', 'nc', 'nd', 'ne', 'nh', 'nj', 'nm', " +
        "'nv', 'ny', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx', 'ut', " +
        " 'va', 'vt', 'wa', 'wi', 'wv', 'wy'")
    elif col == "type":
        print("valid types: 'apartment', 'assisted living', 'condo', 'cottage/cabin', 'duplex', " +
        "'flat', 'house', 'in-law', 'land', 'loft', 'manufactured', 'townhouse'")
    else:
        print("valid keys: 'state', ' type'\n")
        sandbox_generator_help('state')
        print("")
        sandbox_generator_help('type')

In [89]:
sandbox_generator_help()

valid keys: 'state', ' type'

valid states: 'ak', 'al', 'ar', 'az', 'ca', 'co', 'ct', 'dc', 'de', 'fl', 'ga', 'hi', 'ia', 'id', 'il', 'in', 'ks', 'ky', 'la', 'ma', 'md', 'me', 'mi', 'mn', 'mo', 'ms', 'mt', 'nc', 'nd', 'ne', 'nh', 'nj', 'nm', 'nv', 'ny', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx', 'ut',  'va', 'vt', 'wa', 'wi', 'wv', 'wy'

valid types: 'apartment', 'assisted living', 'condo', 'cottage/cabin', 'duplex', 'flat', 'house', 'in-law', 'land', 'loft', 'manufactured', 'townhouse'