In [1]:
import duckdb
import pandas as pd

In [2]:
con = duckdb.connect('data/exploitation.db', read_only=True)

In [3]:
con.execute("show tables").df()

                                      name
0                                   houses
1  sandbox_T_apartment_condo_S_ga_fl_nc_sc

In [11]:
#con.execute("show select * from  houses").df()
con.execute("select * from  houses limit 10").df()

,id,url,region,region_url,price,type,sqfeet,beds,baths,cats_allowed,...,hospital_type_children,government_hospital,nonprofit_hospital,private_hospital,num_schools,num_students,preschool,elementary_school,middle_school,high_school
0,7051152434,https://portland.craigslist.org/wsc/apa/d/port...,portland,https://portland.craigslist.org,1350.0,apartment,1100.0,2,2.0,Yes,...,1.0,3.0,13.0,2.0,403,240366.0,261.0,64.0,61.0,14.0
1,7051146105,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2725.0,apartment,1172.0,2,2.0,Yes,...,1.0,4.0,16.0,2.0,509,309619.0,312.0,81.0,84.0,30.0
2,7051135375,https://portland.craigslist.org/wsc/apa/d/hill...,portland,https://portland.craigslist.org,1630.0,apartment,1030.0,2,2.0,Yes,...,3.0,12.0,48.0,6.0,1431,851145.0,888.0,222.0,237.0,78.0
3,7051134300,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1768.0,apartment,1286.0,2,2.5,Yes,...,44.0,88.0,352.0,88.0,13640,8113424.0,8404.0,2288.0,2332.0,528.0
4,7051104814,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1384.0,apartment,533.0,0,1.0,Yes,...,6.0,24.0,96.0,12.0,3012,1826880.0,1836.0,480.0,504.0,180.0
5,7051112739,https://portland.craigslist.org/clk/apa/d/vanc...,portland,https://portland.craigslist.org,3250.0,house,2895.0,4,3.0,Yes,...,1.0,4.0,10.0,1.0,335,193095.0,193.0,55.0,60.0,26.0
6,7039764729,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,1640.0,apartment,1204.0,3,2.0,Yes,...,3.0,12.0,48.0,6.0,1488,892032.0,921.0,234.0,243.0,81.0
7,7051064155,https://portland.craigslist.org/clc/apa/d/wils...,portland,https://portland.craigslist.org,1515.0,apartment,1045.0,2,2.0,Yes,...,44.0,88.0,352.0,88.0,13640,8113424.0,8404.0,2288.0,2332.0,528.0
8,7051050052,https://portland.craigslist.org/mlt/apa/d/port...,portland,https://portland.craigslist.org,2200.0,duplex,1100.0,3,2.0,No,...,6.0,24.0,96.0,12.0,3012,1826880.0,1836.0,480.0,504.0,180.0
9,7045835490,https://portland.craigslist.org/mlt/apa/d/gres...,portland,https://portland.craigslist.org,1205.0,apartment,865.0,2,1.0,Yes,...,4.0,16.0,60.0,8.0,1988,1206692.0,1192.0,328.0,336.0,124.0

In [3]:
con.close()